analysis_options:
  linter:
    rules:
      - avoid_print          # Avoid using print statements for debugging
      - avoid_redundant_argument_values # Avoid redundant argument values
      - avoid_slow_async      # Avoid using slow async functions
      - camel_case_types     # Enforce camelCase for types (classes, enums)
      - constant_identifier_names  # Enforce constant naming conventions
      - control_flow_analysis  # Improves analysis of control flow
      - curly_braces         # Enforce curly braces for control flow statements
      - dead_code            # Detects dead code (unreachable code)
      - avoid_empty_constructor # Avoid empty constructors
      - empty_statements     # Avoid empty statements
      - equal_identifiers    # Detects identifiers that differ only in case
      - inference_capture    # Improves type inference
      - iterable_cast        # Improves analysis of iterables
      - list_にならない  # Detects usage of non-Flutter specific list methods (Japanese rule)
      - non_constant_identifier_names  # Enforce non-constant naming conventions
      - null_check_operators  # Enforce null-check operators
      - prefer_final_locals   # Prefer using final or const for local variables
      - prefer_if_null_operator # Prefer using the if-null operator
      - prefer_single_quotes  # Prefer using single quotes for strings
      - sort_constructors_first  # Sort constructors first in classes
      - type_annotate_public_apis # Enforce type annotations for public APIs
      - unawaited_futures    # Detects unawaited futures
      - use_key_in_widget_constructors # Enforce using a key in widget constructors
      - use_super_parameters  # Enforce using super parameters in constructors

# Additional rules you might consider:
# - avoid_catching_errors  # Consider for error handling strategies
# - avoid_positional_bool_parameters # Optional rule for readability
# - long_parameter_list   # Optional rule to limit parameter count per function

# You can disable specific rules if needed
# - rules:
#     - avoid_print: false  # Disable avoid_print rule
